# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[[override]]
  name = "github.com/spf13/pflag"
  version = "v1.0.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.3"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/knative/eventing"
  version = "v0.2.1"

[[constraint]]
  name = "github.com/knative/serving"
  version = "v0.2.2"

[[constraint]]
  name = "github.com/knative/build"
  version = "v0.2.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.5.0"
  
[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.4.0"

# Buildpack build support
[[constraint]]
  name = "github.com/buildpack/pack"
  version = "v0.0.7"
[[override]]
  name = "github.com/buildpack/lifecycle"
  revision = "fa66d9071434462f2b9c0a0d6668be36c165fd73"
[[override]]
  name = "github.com/buildpack/packs"
  revision = "aa30a412923763df37e83f14a6e4e0fe07e11f25"
[[override]]
  name = "github.com/docker/docker"
  revision = "b8e87cfdad8daa6ef782ddb90691a259483bc8e4"
[[override]]
  name = "github.com/google/go-containerregistry"
#  revision = "eb57122f1bf944d0584c387c62c1a759c953684d" # This is what pack@0.0.7 references, but doesn't compile here
  revision = "74aef1a35cfa25a5a20c951199abd26356e7bead"  # This is what lifecyle@fa66d9 references
[[override]]
  name = "github.com/sclevine/spec"
  version = "v1.0.0"
# /end of buildpack/pack induced overrides
