{{- if .Values.create.faas -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-event-dispatcher
  labels:
    app: {{ template "name" . }}
    component: event-dispatcher
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.eventDispatcher.service.type }}
  ports:
    - port: {{ .Values.eventDispatcher.service.externalPort }}
      targetPort: {{ .Values.eventDispatcher.service.internalPort }}
      protocol: TCP
      name: {{ .Values.eventDispatcher.service.name }}
  selector:
    app: {{ template "name" . }}
    component: event-dispatcher
    release: {{ .Release.Name }}
{{- end -}}
