apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
    component: zipkin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
        component: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9411
        env:
        - name: JAVA_TOOL_OPTIONS
          value: '-Xmx512m'
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
