apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: sentiments
spec:
  image: sk8s/sentiments:v0001
  protocol: stdio
  input: tweets
  output: sentiments
  env:
  - name: FUNCTION_URI
    value: file:///functions/python/sentiment_service.py?handler=sentiment_service.process
