apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: wordcount
spec:
  image: sk8s/wordcount:v0001
  protocol: stdio
  input: names
  output: greetings
  env:
  - name: FUNCTION_URI
    value: /functions/script/wordcount.sh
