apiVersion: v1
kind: Service
metadata:
  name: topic-controller
  labels:
    app: riff
    component: topic-controller
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    component: topic-controller
