apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: topic-gateway
spec:
  replicas: 1
  template:
    metadata:
      name: topic-gateway
      labels:
        app: topic-gateway
    spec:
      containers:
      - image: sk8s/topic-gateway:0.0.1-SNAPSHOT
        name: topic-gateway
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_TOOL_OPTIONS
          value: '-Xmx512m'
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: kafka:9092
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
          value: zookeeper:2181
